create table public.market_briefs (
  id uuid primary key default gen_random_uuid(),
  squad_player_slug text,
  scouted_target_id uuid references public.scouted_targets(id) on delete set null,
  freetext_player   jsonb,
  constraint market_briefs_player_identity_chk check (
    (squad_player_slug is not null)::int +
    (scouted_target_id  is not null)::int +
    (freetext_player    is not null)::int = 1
  ),
  country     text  not null,
  tier_filter int[] not null default '{1,2}',
  angle       text  not null default 'market_fit',
  constraint market_briefs_angle_chk check (
    angle in ('market_fit', 'valuation', 'risk', 'pitch_strategy')
  ),
  budget_hint text,
  brief_json        jsonb,
  assembled_context text,
  source_status     jsonb,
  generated_by          uuid references auth.users(id) on delete set null,
  generated_at          timestamptz not null default now(),
  duration_ms           int,
  model                 text,
  system_prompt_version text not null default 'v1.0',
  web_search_enabled    bool default true,
  total_input_tokens    int,
  total_output_tokens   int,
  total_search_calls    int
);

alter table public.market_briefs enable row level security;

create policy "market_briefs_admin_all"
  on public.market_briefs
  for all
  to authenticated
  using (is_admin())
  with check (is_admin());

create index idx_market_briefs_country_time
  on public.market_briefs (country, generated_at desc);

create index idx_market_briefs_user_time
  on public.market_briefs (generated_by, generated_at desc);

create index idx_market_briefs_scouted_target_time
  on public.market_briefs (scouted_target_id, generated_at desc)
  where scouted_target_id is not null;

create index idx_market_briefs_squad_player_time
  on public.market_briefs (squad_player_slug, generated_at desc)
  where squad_player_slug is not null;

comment on table public.market_briefs is
  'Country Market Briefs — generated by the generate-market-brief edge function. One row per (player, country) brief run. Mirrors club_briefs.';